Merge pull request #1 from k22rs120/update
smkwlab/ise-report-template pull request #22
Opened 2024-07-15 09:45 UTC by k22rs120

READMEに以下の内容を追加した。
・作成したタグをリモートへプッシュする方法

forkを使用して新しい子のリポジトリからpull requestをするつもりでしたが、手違いで直接親リポジトリをmarge pull requestしてしまいました。一度実行したmargeを、Revertして新たにpull requestを実行しています。

2024-07-15 09:52 UTC, k22rs120 commented
No reviewsですが私がmargeしてもよろしいでしょうか？

2024-07-15 11:08 UTC, toshi0806 commented
From: k22rs120 ***@***.***>
Subject: Re: [smkwlab/ise-report-template] Merge pull request #1 from k22rs120/update (PR #22)
Date: Mon, 15 Jul 2024 02:52:57 -0700

> No reviewsですが私がmargeしてもよろしいでしょうか？

だめです。
--
しもかわとしひこ

2024-07-17 04:20 UTC, toshi0806 requested changes
`ボタンをクリック`だけだと、理由がわからないので、その後に、`リモートリポジトリーに Push`のような内容を付加したほうが良いと思います。

2024-07-18 16:03 UTC, k22rs120 commented
README内の一文を以下の内容に修正した。
・タグがローカルに保存された後、GitHub Desktopの右上にある`Push`ボタンをクリックしてリモートリポジトリにPush

再レビューをお願いします。

2024-07-19 00:12 UTC, toshi0806 requested changes
少なくとも89行から92行は、88行の子項目とするのが正しいと思います。
したがって、元のように一段インデントを深くしたほうが良いと思います。
93行については、88行とは独立しているので、現在のインデントの位置のほうが適切だと思います。

2024-07-19 05:36 UTC, k22rs120 commented
README内について以下の内容を修正した。
・インデントを適切な位置に修正した

再レビューをお願いします。

2024-07-20 06:59 UTC, toshi0806 approved these changes
修正提案ありがとう。

2024-07-20 06:59 UTC, merged